### ISSUE TITLE
How to disable swipe Up and swipe Down?

### ISSUE THREAD

**Issue by captainflo** [3DJakob/react-tinder-card#1]
Hi Jakob Unnebäck, is it possible to disable the swipe up and down?

**Comment by 3DJakob** [comment]
No there is no such function implemented at this time. However, it would be really easy to add is this something you would like to see?

**Comment by exneval** [comment]
@3DJakob yes please, looking for it

**Comment by 3DJakob** [comment]
@exneval @captainflo This feature has now been added. There is a new `preventSwipe` that takes an array of directions.

`<TinderCard onSwipe={onSwipe} onCardLeftScreen={() => onCardLeftScreen('fooBar')} preventSwipe={['right', 'left']}>Hello, World!</TinderCard>`

Happy coding!

**Comment by captainflo** [comment]
Thank You! 👍
