### ISSUE TITLE
incompatible with react@18.2.0

### ISSUE THREAD

**Issue by Gautam-Ghai** [3DJakob/react-tinder-card#100]
Can't install it with react 18.2.0
![Screenshot 2022-07-07 113923](https://user-images.githubusercontent.com/70984665/177846195-f156b369-6ed3-4033-a8fc-526fb87c9c9c.png)

**Comment by Gautam-Ghai** [comment]
did work with --force though!!!

**Comment by Datta2119** [comment]
It installs properly with the following command:
**'npm isntall --global react-tinder-card'**

but after that the **Module not found error** occured
![react-tinder-card](https://user-images.githubusercontent.com/104709987/178092734-fc1e2b50-d719-40c3-b6de-b32f578dd057.png)

**Comment by LinusU** [comment]
Should be fixed by #110

**Comment by LinusU** [comment]
This should be fixed in 1.5.2 🎉

**Comment by 3DJakob** [comment]
> It installs properly with the following command: **'npm isntall --global react-tinder-card'**
> 
> but after that the **Module not found error** occured ![react-tinder-card](https://user-images.githubusercontent.com/104709987/178092734-fc1e2b50-d719-40c3-b6de-b32f578dd057.png)

You definitely should not install this module with --global since your project wont include the module later if somebody else tries to run it.

As @LinusU this is fixed in 1.5.2. Just install the latest version by running `npm install react-tinder-card` and all should be working!
