### ISSUE TITLE
react-spring: Directly calling start instead of using the api object is deprecated in v9 (use ".start" instead)

### ISSUE THREAD

**Issue by mdp18** [3DJakob/react-tinder-card#101]
Any idea's on how to fix this to ensure I don't end up breaking it on update?

`react-spring: Directly calling start instead of using the api object is deprecated in v9 (use ".start" instead)`

**Comment by mdp18** [comment]
@3DJakob -- Any help would be great.

**Comment by 3DJakob** [comment]
@mdp18 Hello! I have a lot of other things right now so cannot update this right now. PRs however are welcome so if you or anyone else wants to update this that would be great. Just make sure to follow the [contribution guide](https://github.com/3DJakob/react-tinder-card/blob/master/CONTRIBUTING.md).  In the meantime, I suggest you simply install the previous version of react-spring and everything should work as expected.

**Comment by 3DJakob** [comment]
@mdp18 I have now fixed this issue and it is released in 1.5.1 🎉 Run ``npm install react-tinder-card@1.5.1`` and it will work.

**Comment by mdp18** [comment]
Amazing. Thanks for doing this :)
