### ISSUE TITLE
Keyboard arrow keys support?

### ISSUE THREAD

**Issue by Codemaine** [3DJakob/react-tinder-card#103]

**Comment by 3DJakob** [comment]
@Codemaine this is something you could implement using the `swipe([dir])` API. Just like how the buttons in the demo repository swipes cards onClick you could add a `keydown` listener to the window on web to swipe on arrow presses. For example code how to programmatically swipe cards check [this snippet](https://github.com/3DJakob/react-tinder-card-demo/blob/b187f4d54e19b25fcdccf7e30d96835ada3ed582/src/examples/Advanced.js#L66).

**Comment by Codemaine** [comment]
Thanks, I actually just figured that out 😅
