### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'style')

### ISSUE THREAD

**Issue by dnish** [3DJakob/react-tinder-card#106]
Hey,
thank you for the great component. We currently tried to implement it, but getting the following error when we create a new array after a user has swiped all available users:

```
TypeError: Cannot read properties of null (reading 'style') 
```

It's happening here:

```
   element.current.style.display = 'none'
      if (onCardLeftScreen) onCardLeftScreen(dir)
```

I guess the problem is that the animation is running while the component gets unmuted because of the new array. Maybe we can check if the element.current is still defined before we apply the style.

**Comment by 3DJakob** [comment]
When using `useRef` you should always check that `element.current != null` before accessing it because there are no guarantees that the element actually exists in the DOM.

Does that help?

**Comment by 3DJakob** [comment]
Perfect!
