### ISSUE TITLE
Possible solution for handling click inside the card?

### ISSUE THREAD

**Issue by dnish** [3DJakob/react-tinder-card#107]
Hey @3DJakob,
just saw a lot of issues about handling clicks within the cards. I've just tested a little bit and came to the result, that only the <code>ev.preventDefault</code> of the touchstart and touchend event listeners causes the issue. If we let the <code>ev.preventDefault</code> within the touchmove handler active, everything still seems to work fine. So I'm wondering if there are any downsides of that solution? Do we really need a <code>ev.preventDefault</code> during the start and end?

**Comment by dnish** [comment]
@3DJakob Yes, tested it on both platforms. The <code>ev.preventDefault</code> within the <code>touchmove</code> seems to be the only one that is needed, because otherwise we would navigate back on iOS devices during a swipe to the right.

**Comment by 3DJakob** [comment]
Hm interesting. That sounds great! If you want to you could create a pull request for this and I will gladly merge it if it works!

Just make sure to check the [CONTRIBUTING.md](https://github.com/3DJakob/react-tinder-card/blob/master/CONTRIBUTING.md)

**Comment by 3DJakob** [comment]
Ok then just use `onTouchStart` or `onTouchEnd ` like suggested in many duplicates of this issue like [#37](https://github.com/3DJakob/react-tinder-card/issues/37) This is a problem with the event listeners interfering with each other. In the future I may find a better solution.

**Comment by 3DJakob** [comment]
The problem with that sollution is that if the window can scroll it will scroll when dragging the card as explained in my reply in #37. So unfortunately this is not a solution. 🤔

**Comment by dnish** [comment]
@3DJakob Mhh tested it on iOS and Android. We don‘t have any scrolling issues. We use the cards as main element on a page with 100% width and height.
