### ISSUE TITLE
Drag jittery

### ISSUE THREAD

**Issue by TimNZ** [3DJakob/react-tinder-card#111]
https://www.loom.com/share/10e3be9c1d824dd2a3aecd4844b6d084

Can the drag be made buttery smooth or should I use react-spring/react-use-gesture directly?

**Comment by 3DJakob** [comment]
It's unfortunately jittery on desktops with large screens. It was initially optimized for mobile. The native version is already updated to use react-spring and it is my goal to make the web version use it as well however that will take some time.

**Comment by jeffceriello** [comment]
Hi there,

any update on this upgrade?

It would be great to have it animate smoothly on desktop too.

Thanks!

**Comment by 3DJakob** [comment]
@jeffceriello This was resolved a long time ago. If you are running the latest it shouldn't be a problem. Look at the demo page if you also have the issue over there. https://3djakob.github.io/react-tinder-card-demo/
