### ISSUE TITLE
Incorrect behavior of the card when double-tapping

### ISSUE THREAD

**Issue by MrPikokon-creator** [3DJakob/react-tinder-card#114]
In the demo project, each card has text. Try to press it with two fingers of one hand. The card is going crazy.

**Comment by MrPikokon-creator** [comment]
Not only in the demo. The problem is with the library itself.

**Comment by MrPikokon-creator** [comment]
https://user-images.githubusercontent.com/63126813/195909583-3a4ec3cd-9923-4026-9d60-0e58f4ac61c7.mp4

**Comment by MrPikokon-creator** [comment]
https://user-images.githubusercontent.com/63126813/195910621-3f86daa6-2dd2-4c30-a8f8-592c3dfa3c6d.mp4

**Comment by 3DJakob** [comment]
This should be fixed in 1.6.0 🎉 Feel free to reopen if not 👍
