### ISSUE TITLE
'requestAnimationFrame' handler took <N>ms violation on every swipe

### ISSUE THREAD

**Issue by strangecarr** [3DJakob/react-tinder-card#123]
Hi have a web app in development for swiping through local events. Visually it's looking pretty good and functionally it works well - but performance isn't great and the card is quite glitchy when it is touched/dragged/swiped. On every swipe I get 10-15  of the following verbose warnings in the console:
'requestAnimationFrame' handler took <N>ms

Each individual warning is between 50ms - 200ms.

Has anyone else seen this in console, an if so, any suggestions to address the issue?

On each card, there is a toggle that renders a map (by mapbox) but I disabled this feature and I'm still getting the violations.

**Comment by 3DJakob** [comment]
Strange sounds like it is related to mapbox. Perhaps you could display images of maps on the cards instead? Many map APIs have this feature. Could you try altogether commenting out your mapbox code to see if it is the code causing it?

**Comment by strangecarr** [comment]
thanks - can confirm the warning still comes even when the mapbox code is commented out (although mapbox do serve static images so will switch that). The warnings appear just after a card leaves the screen. The container for my cards is a grid -
