### ISSUE TITLE
Card content unclickable on mobile

### ISSUE THREAD

**Issue by danieltpham** [3DJakob/react-tinder-card#13]
What a fantastic module! Thank you!

I'm currently implementing a hyperlink in the Cards, and on desktop it works well, but somehow they are unclickable on mobile view. Could you please help with this issue?

**Comment by 3DJakob** [comment]
Hey @danieltpham glad you found the module useful and sorry for the late reply! I haven't had the problem myself so its hard to locate the exakt problem but my guess is that it have to do with the position absolute positioning. Try adding a positive z-index and se if it resolves the problem. Please give it a shot and tell me if it works!

**Comment by CanberkUcar** [comment]
I'm having the same issue with positive Z-Index. It resolved on disabling the preventDefaults on source code it self.
