### ISSUE TITLE
In 1.6.2, swipe right cards do not leave screen (occurs on demo site too)

### ISSUE THREAD

**Issue by magnum6actual** [3DJakob/react-tinder-card#131]
This just started happened on my app and I see it happening on the demo site as well. When you swipe right on a card, either through drag or the swipe button, the card never leaves the screen.  See linked video of behavior.  I tried to drop back down to 1.5.4, but had other problems.

https://youtube.com/shorts/gxZFZR8fnyE

**Comment by magnum6actual** [comment]
Misunderstanding. Closed

**Comment by 3DJakob** [comment]
You need to add `overflow: hidden;` on your `<body>` Cards are only completely removed if you remove them from the input data set.
