### ISSUE TITLE
OnSwipe Function Triggering   3 or 2 time   on single Swipe 

### ISSUE THREAD

**Issue by nikhilrizal** [3DJakob/react-tinder-card#138]
I m using react tinder card on Nextjs 

So whenever  the user Swipes the card on right side i m making api call to post some data to bankend but ,the problem is that is getting posted twice on one swipe  !

**Comment by DoxasticFox** [comment]
For web, I solved it by changing [this](https://github.com/3DJakob/react-tinder-card/blob/bcc802c600c3ec348de7ae31bfcb3a32da051560/index.js#L241) line to pass a second argument, `[]`. That causes the stuff that `useLayoutEffect` executes to only be executed once, when the `TinderCard` component is first mounted. I don't see any similar issues in the [react native](https://github.com/3DJakob/react-tinder-card/blob/bcc802c600c3ec348de7ae31bfcb3a32da051560/index.native.js#L153) implementation, but I'll check shortly and post back if I have any fixes.

**Comment by mhk4022** [comment]
I could not solve the problem. Could you please give me more details on the solution?

**Comment by DoxasticFox** [comment]
@mhk4022 I raised a PR: https://github.com/3DJakob/react-tinder-card/pull/140

**Comment by mhk4022** [comment]
Thank you!

**Comment by ranjitbudhathoki** [comment]
any idea how to solve this problem?

**Comment by ranjitbudhathoki** [comment]
@DoxasticFox  Thank you

**Comment by ranjitbudhathoki** [comment]
@DoxasticFox  This doesn't seem to be a permanent solution when i reload my application it again sends too many requests

**Comment by di-sukharev** [comment]
please fix this, PR is ready https://github.com/3DJakob/react-tinder-card/pull/140/files

**Comment by jvondermarck** [comment]
I have the same issue, could someone just merge the PR ???

**Comment by 3DJakob** [comment]
This has been fixed in version 1.6.4. Feel free to reopen if the issue persists.

**Comment by jvondermarck** [comment]
Hi @3DJakob, I just tested on my Next.JS app and it is working really good ! Thank you so much !!
