### ISSUE TITLE
I'm creating a deck of flippable card.

### ISSUE THREAD

**Issue by baulagerwin** [3DJakob/react-tinder-card#142]
Hello. I'm so grateful for this library. It really helps me swipe my cards on to the left and right. However, I notice that the pressable prop is not working. I tried adding it to the className but didn't work. The reason I want it to work is because I want that card to be flippable.  

Here's what I did: <TinderCard className="pressable"><SomeComponent/></TinderCard>

But this didn't work. I tried adding the onTouchStart event outside and inside the TinderCard component but that's where the swipe begins to not work.  Is there any solution for it to work on mobile? If there's not its okay. I'm beyond grateful already for the swipe  functionality.

That's it. Have a good day!

**Comment by azwinlam** [comment]
I'm trying to navigate prop to the Text onPress and having the same issues. If you figured it out, please shout out. 

Wrapping the text in TouchableOpacity I can see the text fade, but it doesn't even trigger console.log("did I press")

**Comment by baulagerwin** [comment]
I haven't figured it out. I believe it is not working. I managed to build the feature I want without the working with pressable prop. I'm sorry man I couldn't be more helpful.

**Comment by azwinlam** [comment]
Thanks for leaving a reply.

I tried the following

https://github.com/3DJakob/react-tinder-card/issues/86

Works on the iOS simulator.. I tried the patch package, not working on the apk yet.

**Comment by 3DJakob** [comment]
If this is on native this should be fixed by updating to 1.6.3.

**Comment by 3DJakob** [comment]
Closing this feel free to reopen if 1.6.3 does not resolve the issue.
