### ISSUE TITLE
Click and dragging a card for a few seconds leads to warning and then freezes

### ISSUE THREAD

**Issue by edmondtam1** [3DJakob/react-tinder-card#144]
Hi,

Thank you for the lovely component! It's wonderfully simple to use and implement.

**Problem**

On my website and the test website (https://3djakob.github.io/react-tinder-card-demo/), there is a warning that appears after holding onto a card (and shaking it a little) for too long:

<img width="701" alt="image" src="https://user-images.githubusercontent.com/11762093/224377742-c17cce2b-c024-47de-9cec-9057b30c9400.png">

After this warning, the card freezes and then disappears.

**Other context**

I'm wondering if this is due to any updates to React or its compatibility with `@react-spring`? This guess is based on this issue on `react-timekeeper` here: https://github.com/catc/react-timekeeper/issues/85. 

It doesn't happen when using the demos in `@react-spring`, however (see https://www.react-spring.dev/examples). 

Any ideas on how we can address this will be very much appreciated, and thanks again for the package!

**Comment by 3DJakob** [comment]
Hey @edmondtam1 sorry for the very late reply. But I noticed this as well. Perhaps this would be resolved if the spring version was updated. I will look at it, but if someone beats me to it PRs are welcome.

**Comment by 3DJakob** [comment]
@edmondtam1  This has been fixed in 1.5.3. Just update and it will work! 👍

**Comment by edmondtam1** [comment]
Appreciate it a lot, thank you @3DJakob!
