### ISSUE TITLE
The message that appears on the card when you swipe right, left or up

### ISSUE THREAD

**Issue by ertandk** [3DJakob/react-tinder-card#149]
Hello
How can I instantly show the message that appears on the card when I swipe right, left or up?
Mechanism;
As in Tinder, I want to print the text LIKE, which increases the opacity on the top left when I hold the card and slide it to the right. How can I do it?
This is the most stable library but I don't know how to add it :(
Thank you to those who made and contributed.

**Comment by BenjaminWaye** [comment]
I used onMouse events but it only works on desktop. OnTouch events for some reason block the Tinder card event handlers

**Comment by 3DJakob** [comment]
You can use the `onSwipeRequirementFulfilled` prop. It fires every time the requirement to execute a swipe has been fulfilled. So when it sends `right` start displaying the heart and on `onSwipeRequirementUnfulfilled` stop displaying it! Hope that helps 😄
