### ISSUE TITLE
Could not resolve "@react-spring/web" imported by "react-tinder-card". Is it installed?

### ISSUE THREAD

**Issue by andythegril** [3DJakob/react-tinder-card#154]
I am doing a Tinder-clone web using Vite, with yarn in Webstorm.
I followed exactly the installation steps.
{
  "dependencies": {
    "@react-spring/web": "^9.5.5",
    "react-tinder-card": "^1.6.2"
  }
}
(also checked package.json)
When I tried importing, this error message showed up.
I'm beat. Please help guys... :(

**Comment by peterszaloczy** [comment]
hey , what solved it for me is to spelled out the exact package when installed, let me know if it helps : npm install --save @react-spring/web@9.5.5

**Comment by andythegril** [comment]
you know, the crazy thing is I restart the project, and it was good to go haha
