### ISSUE TITLE
multiple call onCardLeftScreen and onSwipe when one card left the screen

### ISSUE THREAD

**Issue by armancodv** [3DJakob/react-tinder-card#160]
Problem:
- when swipe one card, the `onCardLeftScreen` and `onSwipe` call multiple times. You can even reproduce it [here](https://3djakob.github.io/react-tinder-card-demo/) by checking log after swiping card.
- There is a real performance issue, since there is no dependency for useLayoutEffect and the event listeners inside it are not removed

**Comment by 3DJakob** [comment]
This has been released in version 1.6.4 🎉
