### ISSUE TITLE
How to fit it inside a Bootstrap Modal?

### ISSUE THREAD

**Issue by lemarcgagnon** [3DJakob/react-tinder-card#17]
Hello,

I just don<t know how to fit the Swiper nicely in the bootstrap.  It only centers on the page width and not into the modal width...

https://codesandbox.io/s/person-swiper-8fzbm

<h1>Card Swiper</h1>
            <div className="tinderCards_cardContainer">
              {people.map(person => (
                <div>
                <TinderCard
                  className="swipe"
                  key={person.name}
                  onSwipe={onSwipe}
                  onCardLeftScreen={() => onCardLeftScreen(person.name)}
                  preventSwipe={["up", "down"]}
                >
                  <div
                    style={{ backgroundImage: `url(${person.url})` }}
                    className="card"
                  >
                    <h3>{person.name}</h3>
                  </div>
                </TinderCard>\
                </div>
              ))}
            </div>

class:

.card {
  position: relative;
  width: 400px;
  padding: 20px;
  max-width: 85vw;
  height: 50vh;
  border-radius: 20px;
  background-size: cover;
  background-position: center;
  -webkit-box-shadow: 10px 10px 5px 0px rgba(0, 0, 0, 0.75);
  -moz-box-shadow: 10px 10px 5px 0px rgba(0, 0, 0, 0.75);
  box-shadow: 10px 10px 5px 0px rgba(189, 155, 155, 0.3);
}

.card > h3 {
  position: absolute;
  bottom: 10px;
  text-align: center;
  color: white;
  padding: 4px 8px 4px 8px;
  border-radius: 10px;
  background-color: rgba(71, 65, 65, 0.733);
  -webkit-box-shadow: 4px 2px 2px 0px rgba(0, 0, 0, 0.5);
  -moz-box-shadow: 4px 2px 2px 0px rgba(0, 0, 0, 0.5);
  box-shadow: 4px 2px 2px 0px rgba(14, 13, 13, 0.5);
}

.tinderCards_cardContainer {
  display: flex;
  justify-content: center;
  margin-top: 10vh;
}
.swipe {
  position: absolute;
}

Please help.

Yours,

Marc

**Comment by 3DJakob** [comment]
Hey sorry for late reply hopefully you got it working. The fix issues like this I would allways recommend just removing stuff untill it works. I got it working by removing unnecessary divs in the card.js file and by adding a width to the first div in the TinderCard. Like this:

```
return (
    <>
      {people.map((person) => (
        <TinderCard
          className="swipe"
          style={{ width: 500 }}
          key={person.name}
          onSwipe={onSwipe}
          onCardLeftScreen={() => onCardLeftScreen(person.name)}
          preventSwipe={["up", "down"]}
        >
          <div
            key={person.name}
            style={{
              backgroundImage: `url(${person.url})`,
              width: 400
            }}
            className="card"
          ></div>
        </TinderCard>
      ))}
    </>
  );
```

**Comment by lemarcgagnon** [comment]
Thank you so much!!!!

I will give it a try...

Thanks again!

Marc
