### ISSUE TITLE
Error in ./~/react-tinder-card/index.js

### ISSUE THREAD

**Issue by kaustubhdhole** [3DJakob/react-tinder-card#18]
It throws this error when I start my app:

Failed to compile.
Error in ./.../react-tinder-card/index.js
Module parse failed: /home/.../ui-repositories/tinder-clone/node_modules/react-tinder-card/index.js Unexpected token (26:42)
You may need an appropriate loader to handle this file type.

Did you ever face this? Also, what is the node and npm versions tested for react-tinder-card.

**Comment by 3DJakob** [comment]
Very strange, haven't seen this problem before. I tried installing react-tinder-card 1.2.0 with react 16.12.0 in the demo repo with no issues. So as far as I could tell this is a problem with your install. Have you managed to resolve the issue?
