### ISSUE TITLE
Deleting cards on swipe?

### ISSUE THREAD

**Issue by UPLukeet** [3DJakob/react-tinder-card#20]
"Note that the component will not remove itself after swipe. If you want that behaviour implement that on the onCardLeftScreen callback."
this is what the documentation states but I can't see how they've down it all the example given does it name the card that's swiped off the screen by its identifier, how are we supposed to delete card elements?

**Comment by 3DJakob** [comment]
Hey! There are multiple ways to do this. I would recommend doing it like this.

Make an array with your cards to be rendered and make it a `state`. Make sure each item has a unique identifier to be used as a key.

Create the `TinderCard` elements using a loop like map where `onCardLeftScreen` runs a delete function with the unique id for each card.

In that delete function remove the card in the state array with the matching id. React will then automatically re-render without that card.

Hope that helps! If you need more help I could send you more concrete code examples.

**Comment by hichemfantar** [comment]
> Hey! There are multiple ways to do this. I would recommend doing it like this.
> 
> Make an array with your cards to be rendered and make it a `state`. Make sure each item has a unique identifier to be used as a key.
> 
> Create the `TinderCard` elements using a loop like map where `onCardLeftScreen` runs a delete function with the unique id for each card.
> 
> In that delete function remove the card in the state array with the matching id. React will then automatically re-render without that card.
> 
> Hope that helps! If you need more help I could send you more concrete code examples.

How do i get the id of the element in the onCardLeftScreen function?

**Comment by 3DJakob** [comment]
Let's soppose your objects has an `.id` attribute in that case you would do it like this.

```
const [myObjects, setMyObjects] = useState([])

const onCardLeftScreen = (id) => {
  setMyObjects(myObjects.filter((obj) => obj.id !== id))
}

return (
  <>
    {myObjects.map((myObject) => <TinderCard onCardLeftScreen={() => onCardLeftScreen(myObject.id)}>Hello World!</TinderCard>)}
  </>
)
```

Hope this helps!
