### ISSUE TITLE
Pass event.target to onSwipe function

### ISSUE THREAD

**Issue by hichemfantar** [3DJakob/react-tinder-card#22]
Is it possible to do this? I would like to pass the key property value to the onSwipe function.
<TinderCard
className="swipe"
key={person.email}
preventSwipe={["up", "down"]}
**onSwipe={(e) => onSwipe(e.target.key)}**
flickOnSwipe={true}
>

**Comment by 3DJakob** [comment]
Just do it like this:

`onSwipe={() => onSwipe(person.email)}`

I would suggest that you add unique keys using UUID. Because the email might not always be unique and might include characters that could cause issues.

**Comment by hichemfantar** [comment]
Cool man thanks! Is there any way to get the direction of the swipe in the oncardleftscreen function?
Because i'm trying to a check when the card leaves the screen to check which direction it was swiped in and then do an different action depending on the swipe direction.

**Comment by 3DJakob** [comment]
Yes! Like this

`onCardLeftScreen = {(dir) => console.log(dir)}`

You can see an example of this on the startpage https://github.com/3DJakob/react-tinder-card
