### ISSUE TITLE
Does this work with React native?

### ISSUE THREAD

**Issue by hichemfantar** [3DJakob/react-tinder-card#28]
if not, are there any plans on making a react native version?

**Comment by 3DJakob** [comment]
Unfortunately not at the time. The module relies very heavily on CSS transitions and will not port easily. Maybe someday if a lot of people request it but for now it is not on the roadmap. Hope you can find another solution!

**Comment by richardwu** [comment]
👍 for porting this to React Native.

**Comment by 3DJakob** [comment]
@hichemfantar @richardwu A react-native version is on the way and soon done! I'm working together with @Mr0cket to make it happen. I will post here once it is ready!

**Comment by hichemfantar** [comment]
This is super exciting, this kind of project is perfect for react native!
Looking forward to it man!

**Comment by 3DJakob** [comment]
@hichemfantar @richardwu The native version is released! At the time being make sure to `npm install react-spring` to make it work correctly. This is a issue with the peer dependency and will be resolved in the future. Here is a native demo repository https://github.com/3DJakob/react-native-tinder-card-demo
