### ISSUE TITLE
Error => Failed to minify the code from this file:  ./node_modules/react-tinder-card/index.js:13 Upon running 'npm run build'

### ISSUE THREAD

**Issue by miguelopes98** [3DJakob/react-tinder-card#35]
So im using create-react-app and im trying to build my app by using 'npm run build' so I can eventually deploy it to firebase.
However, whenever I run this, whether it is with version 1.3.0 or 1.2.0 of react-tinder-card card I get this error:

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/react-tinder-card/index.js:13

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tinder@0.1.0 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tinder@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\migue\AppData\Roaming\npm-cache\_logs\2021-01-19T18_01_12_802Z-debug.log

I've browsed around looking for solutions and read that a lot of the times this could be fixed by upgrading the version of react-scripts to a version above 1.2.0, however I'm using the latest version of it which is the 4th, this makes me look that the problem comes from this package somehow instead of the react-scripts. 

I found out that my problem is in the index.js file of this package, where all of those functions are defined using es6 syntax. I'm not being able to run the 'npm run build' when that syntax is in es6, therefore I just converted all of the functions into es5 syntax, using function(args) {...} but im not being able to convert the async function 'animateOut' to es5 syntax, so that is really all I need.

Can someone help me please? Thank you

**Comment by miguelopes98** [comment]
managed to do it: https://stackoverflow.com/questions/65800013/converting-async-es6-syntax-function-to-es5-syntax-async-function

**Comment by 3DJakob** [comment]
Interesting, I haven't seen the problem personally but I will look into it!
