### ISSUE TITLE
Button don't work on the mobile.

### ISSUE THREAD

**Issue by nkrulikovskiy** [3DJakob/react-tinder-card#37]
I've embed a button on the TinderCard element.
On the desktop, it works fine but on the mobile the button click event don't work.

**Comment by 3DJakob** [comment]
Could you post a snippet of code? Most likely you use a event listener that does not exist on mobile. For instance do not use onClick instead use onPress and see if it resolves your issue. Also if you move your button outside the tinder card does it work then?

**Comment by nkrulikovskiy** [comment]
Hi, @3DJakob 
Thank you for your replying.

I am sharing my code snippet according to your request.


`
import { Button } from "@material-ui/core";
import React, { ReactElement, useState } from "react";
import TinderCard from "react-tinder-card";

interface Props {}

export default function Tinder({}: Props): ReactElement {
  const [count, setCount] = useState(0);
  return (
    <div>
      <TinderCard preventSwipe={["up"]} flickOnSwipe>
        This is tinder card
        <Button onClick={() => setCount((prev) => prev + 1)}>
          Tinder click
        </Button>
        {/* This button don't work on tinder card
        I'm using typescript and it doesn't support onPress function
        */}
        <button onClick={() => setCount((prev) => prev + 1)}>
          default button
        </button>
        count:{count}
      </TinderCard>

      {/* Button works well outside of the tinder */}
      <button onClick={() => setCount((prev) => prev + 1)}>
        default button
      </button>
    </div>
  );
}

`

As you can see, I am using Typescript on React and  'onPress' does not exist on type 'DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>
And on the desktop, the click function works well, but on the mobile this function don't work.

Your npm module is great, and if this issue is solved it will be very helpful for me.

**Comment by 3DJakob** [comment]
Ok interesting! I tried this in the demo repository and this is caused by the `event.preventDefault()` on the `touchstart` and `touchmove` event listeners on the card. If these are removed then it works but that has it's consequences. The window will scroll with your drag movements in that case.

The solution is adding the `onTouchStart` event listener on your button. If the material UI button does not feature this event-listener then just wrap it in a `<a>` tag.

`onTouchStart={() => console.log('hello!')}`

**Comment by nkrulikovskiy** [comment]
Works Perfect.
It works well on the Material ui as well. 
Thank you.

**Comment by jerry-inc** [comment]
I am having the same issue but on React-native

any help will be much appreciated...
