### ISSUE TITLE
Trigger Swipe From Button Click?

### ISSUE THREAD

**Issue by aaronksaunders** [3DJakob/react-tinder-card#4]
First off, thanks for the module and the example, was extremely helpful...

Was digging through the source trying to figure out how to attach buttons and events to trigger the left or right swipe

**Comment by 3DJakob** [comment]
Hey @aaronksaunders! Sorry for the late reply, glad it was helpful. You can find it in the if statement on line 129 in `index.js`.

If you run the code:

```
await animateOut(element, speed)
element.style.display = 'none'
onCardLeftScreen()
```

where element is a ref to the element and speed is an object with x and y coordinates. For swiping right try for instance `{x: 200, y: 0}`.

If this is something you still want I could implement a function `swipe(direction)`. Let me know, happy coding!

**Comment by arunpugahz** [comment]
Hi @3DJakob Great work.
It would be very useful if you could implement this as an inbuilt prop.
Triggering animation on Pressing a button has wide range of use cases.
Thanks in advance.

**Comment by 3DJakob** [comment]
@arunpugahz I'll be sure to look into it and program the feature. However it will take som time as I'm really caught up with other projects right now. Hopefully I can get a patch out next week.

**Comment by arunpugahz** [comment]
> @arunpugahz I'll be sure to look into it and program the feature. However it will take som time as I'm really caught up with other projects right now. Hopefully I can get a patch out next week.

Thanks, Man. Appreciate it.

**Comment by arunpugahz** [comment]
@3DJakob Thanks. Appreciate it.

**Comment by bleeinc** [comment]
Any updates on this functionality? Would be really nice to have as it's a pain without it.

**Comment by 3DJakob** [comment]
@bleeinc Unfortunately not at the moment, I have been really swamped with other projects and this is a low priority for me. But there is clearly a demand for so I will try to look for an implementation a soon as I can!

**Comment by ammyt** [comment]
I also second that feature!

**Comment by 3DJakob** [comment]
@aaronksaunders @arunpugahz @bleeinc @ammyt 
With a smile on my face I can now tell you all that this feature has been added in 1.3.1 🎉

Check out the readme for more info: https://github.com/3DJakob/react-tinder-card
I have also added a more advanced example using swipe buttons: https://github.com/3DJakob/react-tinder-card-demo/blob/master/src/examples/Advanced.js
This example is live on the gh-pages site: https://3djakob.github.io/react-tinder-card-demo/
