### ISSUE TITLE
I am unable to use the onclick even on the mobile screens

### ISSUE THREAD

**Issue by HarshSonawane** [3DJakob/react-tinder-card#47]
I added a button, basically another component, but it is failing to open and accept the onclick event on the mobile screen

**Comment by nkrulikovskiy** [comment]
This issue was suggested already.
https://github.com/3DJakob/react-tinder-card/issues/37#issuecomment-779389381

**Comment by 3DJakob** [comment]
Closing this issue as @nkrulikovskiy linked to the solution
