### ISSUE TITLE
Disable touch/swipe event, use buttons only

### ISSUE THREAD

**Issue by merganon** [3DJakob/react-tinder-card#52]
Is there a way to prevent swipe/touch events on the cards so you can only trigger a swipe by clicking on a component (for example a button) that triggers `swipe("left")` or `swipe("right")` via onClick?

**Comment by 3DJakob** [comment]
You could probably just add a Touchable element as a parent for the cards and run `event.preventDefault()` on the touch event.  Another solution could be adding a large position absolute View on top of the stack preventing touches on the cards below. A boolean could be implemented into the module to temporarily disable the touchPanResponder but it is not a priority right now.
