### ISSUE TITLE
not able to install it 

### ISSUE THREAD

**Issue by Balachandra-14** [3DJakob/react-tinder-card#56]

**Comment by 3DJakob** [comment]
Hello, could you provide more details of the steps you have done and what environment you are running i.e. React Native or React.

**Comment by Balachandra-14** [comment]
Thank you for your response but got to know how to use it

**Comment by alowenthal** [comment]
I also could not successfully install. Referring to React version, running node v16.5.0. I ran this command line: `npm i react-tinder-card`

**Comment by nikeee** [comment]
Maybe you should pass `--legacy-peer-deps` when installing.

**Comment by 3DJakob** [comment]
Glad you resolved the issue 👍
