### ISSUE TITLE
Bring back Swiped cards [Feature request]

### ISSUE THREAD

**Issue by arunpugahz** [3DJakob/react-tinder-card#58]
Is there a way to bring back the swiped cards? Like the rewind functionality on Tinder

**Comment by akafaneh** [comment]
an undo kinda, also kinda needed that, other than to give the option to the user but also to handle api errors more gracefully and giving the user second chance to swipe again.

**Comment by 3DJakob** [comment]
There is an open PR for this https://github.com/3DJakob/react-tinder-card/pull/46/ I have been really swamped lately so I'm a bit behind on this repo. I will try to take a look at this asap. In the meantime, you could simply replace the module code with that fork. I will post a comment here once it is merged.

**Comment by 3DJakob** [comment]
This update has been released now! 🎉 
To use is update your version by running `npm install react-tinder-card`

**Comment by 3DJakob** [comment]
This update has been released now! 🎉 
To use is update your version by running `npm install react-tinder-card`
