### ISSUE TITLE
Please publish a new package with type update?

### ISSUE THREAD

**Issue by sarah1446** [3DJakob/react-tinder-card#59]
Hello!
Could you publish npm latest version including "className?: string"?
I think 1.4.0 version still doesn't provide attribute class type.
https://github.com/3DJakob/react-tinder-card/blob/7496b4cc513b28d9ddcdecdcbd1c9ce9b347d285/index.d.ts#L46

**Comment by 3DJakob** [comment]
This has been published now along with the `restoreCard` feature!
