### ISSUE TITLE
TinderCard makes component  unclickable

### ISSUE THREAD

**Issue by iChristosK** [3DJakob/react-tinder-card#79]
I have routerLink inside my component, on the emulator, it doesn't work. Is there a way to make the TinderCard clickable?

` <TinderCard
                  flickOnSwipe={true}
                  onSwipeRequirementFulfilled={() => onSwipeFulfilled()}
                  onCardLeftScreen={() => onCardLeftScreen(index)}
                  preventSwipe={['up', 'down']}
                  swipeThreshold={300}
                >
                  <CustomListing
                  />
                </TinderCard>`

And inside custom Listing 
`<IonCard routerLink="/detailed"></IonCard`

Which now doesn't work.

**Comment by 3DJakob** [comment]
Hello Christos, Please check out my response here
https://github.com/3DJakob/react-tinder-card/issues/79


Jakob Unnebäck

Film maker & Web developer @ Unga Utvecklare

filmpåriktigt.se


Den mån 27 dec. 2021 kl 10:42 skrev Christos ***@***.***>:
