### ISSUE TITLE
Add style= parameter

### ISSUE THREAD

**Issue by suiramdev** [3DJakob/react-tinder-card#82]
Hello there.
Instead of using an `<img/>` element inside my TinderCard, I would've loved to modify its background image dynamically. However, react-tinder-card doesn't permit to add styling but only classes.
Could it be had?

Thank you.

**Comment by 3DJakob** [comment]
Just add a div inside with a background image like normal. The module is designed to do functionality only, with no styling. You add your own card component with style. Here is from the simple example demo code:
```
<TinderCard className='swipe' key={character.name} onSwipe={(dir) => swiped(dir, character.name)} onCardLeftScreen=. {() => outOfFrame(character.name)}>
    <div style={{ backgroundImage: 'url(' + character.url + ')' }} className='card'>
        <h3>{character.name}</h3>
    </div>
</TinderCard>
```

https://github.com/3DJakob/react-tinder-card-demo/blob/b187f4d54e19b25fcdccf7e30d96835ada3ed582/src/examples/Simple.js#L49
