### ISSUE TITLE
Feature: Ability to jump to specific card

### ISSUE THREAD

**Issue by jerry-inc** [3DJakob/react-tinder-card#87]
I believe this amazing library will become even more awesome if it could allow jumping to specific cards forward or backward.

For example. If a user is on card 1 of 6, and he wants to go directly to card 4 of 6, etc. Therefore, If swipe with an index or maybe a jumpTo function with an index would be available then this library will be perfect.

**Comment by 3DJakob** [comment]
This library only implements a single card that you can implement many of to make a pile. Therefore you could program that functionality yourself using this module. You could just modify your array that creates the cards to fit whatever order you want at any time.

**Comment by jerry-inc** [comment]
> This library only implements a single card that you can implement many of to make a pile. Therefore you could program that functionality yourself using this module. You could just modify your array that creates the cards to fit whatever order you want at any time.

When I modify the card array, it resets the deck and comes back to back 1. that is why I was suggesting adding an index
