### ISSUE TITLE
Performance issues when you return TinderCard in a map which renders it x20 times - Web iPhone 13 Pro (latest Safari or Chrome).

### ISSUE THREAD

**Issue by ElAndy94** [3DJakob/react-tinder-card#89]
Currently trying to use this to display a total of 20 cards, once they have all been swiped then make a request and load another 20 on the page, upon trying to load the initial set of 20 cards on 'mobile browser' it pretty much dies on me with lag.

**Comment by ElAndy94** [comment]
The only fix around this was to check the array length that I am mapping through, keep track of how many cards I have swiped through, and -2 on that figure so it only renders two cards at a time. The image will be shared to help understand. 
<img width="569" alt="image" src="https://user-images.githubusercontent.com/34091709/156898276-b8949d1a-a558-4903-bf84-4f48a63a5b55.png">

**Comment by 3DJakob** [comment]
Hey @ElAndy94! You should definitely only render the topmost cards if the stack is large. How that implementation is made is up to you! Glad you got it working 👍

This module is solely focused on being a single card to allow for maximum flexibility so making that implementation is beyond the scope of this module.
