### ISSUE TITLE
Incompatible with RN 0.66.0 and React 17.0.2

### ISSUE THREAD

**Issue by roots-ai** [3DJakob/react-tinder-card#91]

**Comment by seeker-3** [comment]
React 18 now needs to you explicitly add a children property e.g. `{children?: ReactNode}`. I got this type error when I upgraded react.
<img width="398" alt="Screen Shot 2022-06-01 at 2 53 44 PM" src="https://user-images.githubusercontent.com/31900513/171480957-2ffe0e41-ea09-40e2-8a11-1011d7cb2766.png">

Workaround
```ts
type TinderCardProps = Parameters<typeof TinderCard>[0]
type TinderCardPropsWithChildren = FC<
  TinderCardProps & { children?: ReactNode }
>

const TinderCardWithChildren: TinderCardPropsWithChildren = TinderCard
```

**Comment by KrishnaM251** [comment]
Worked like a charm! Just didn't realize that you were supposed to use `TinderCardWithChildren` in place of the normal `TinderCard`.
