### ISSUE TITLE
Cannot change state

### ISSUE THREAD

**Issue by kunalBasnetC** [3DJakob/react-tinder-card#93]
The state cannot be updated on calling onSwipe method and swiping right and left from desktop view.

**Comment by 3DJakob** [comment]
The `onSwipe` is a callback, not a method of swiping itself. It gets invoked once you swipe a card. If you want to programatically swipe a card you need to look at the `swipe` function in the API section of the doc. Check out the demo code [here](https://github.com/3DJakob/react-tinder-card-demo/blob/b187f4d54e19b25fcdccf7e30d96835ada3ed582/src/examples/Advanced.js#L68) if you need more help implementing it.
